
package ru.naumkin.tm.api.endpoint;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.3.6
 * 2020-05-22T19:31:29.064+07:00
 * Generated source version: 3.3.6
 */

@WebFault(name = "ClassNotFoundException", targetNamespace = "http://endpoint.api.tm.naumkin.ru/")
public class ClassNotFoundException_Exception extends java.lang.Exception {

    private ru.naumkin.tm.api.endpoint.ClassNotFoundException classNotFoundException;

    public ClassNotFoundException_Exception() {
        super();
    }

    public ClassNotFoundException_Exception(String message) {
        super(message);
    }

    public ClassNotFoundException_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public ClassNotFoundException_Exception(String message, ru.naumkin.tm.api.endpoint.ClassNotFoundException classNotFoundException) {
        super(message);
        this.classNotFoundException = classNotFoundException;
    }

    public ClassNotFoundException_Exception(String message, ru.naumkin.tm.api.endpoint.ClassNotFoundException classNotFoundException, java.lang.Throwable cause) {
        super(message, cause);
        this.classNotFoundException = classNotFoundException;
    }

    public ru.naumkin.tm.api.endpoint.ClassNotFoundException getFaultInfo() {
        return this.classNotFoundException;
    }
}
