
package ru.naumkin.tm.api.endpoint;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.3.6
 * 2020-05-22T19:31:29.056+07:00
 * Generated source version: 3.3.6
 */

@WebFault(name = "IOException", targetNamespace = "http://endpoint.api.tm.naumkin.ru/")
public class IOException_Exception extends java.lang.Exception {

    private ru.naumkin.tm.api.endpoint.IOException ioException;

    public IOException_Exception() {
        super();
    }

    public IOException_Exception(String message) {
        super(message);
    }

    public IOException_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public IOException_Exception(String message, ru.naumkin.tm.api.endpoint.IOException ioException) {
        super(message);
        this.ioException = ioException;
    }

    public IOException_Exception(String message, ru.naumkin.tm.api.endpoint.IOException ioException, java.lang.Throwable cause) {
        super(message, cause);
        this.ioException = ioException;
    }

    public ru.naumkin.tm.api.endpoint.IOException getFaultInfo() {
        return this.ioException;
    }
}
