package ru.naumkin.tm.api.endpoint;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.6
 * 2020-05-27T18:06:30.972+07:00
 * Generated source version: 3.3.6
 *
 */
@WebService(targetNamespace = "http://endpoint.api.tm.naumkin.ru/", name = "ISessionEndpoint")
@XmlSeeAlso({ObjectFactory.class})
public interface ISessionEndpoint {

    @WebMethod
    @Action(input = "http://endpoint.api.tm.naumkin.ru/ISessionEndpoint/validateRequest", output = "http://endpoint.api.tm.naumkin.ru/ISessionEndpoint/validateResponse", fault = {@FaultAction(className = Exception.class, value = "http://endpoint.api.tm.naumkin.ru/ISessionEndpoint/validate/Fault/Exception")})
    @RequestWrapper(localName = "validate", targetNamespace = "http://endpoint.api.tm.naumkin.ru/", className = "ru.naumkin.tm.api.endpoint.Validate")
    @ResponseWrapper(localName = "validateResponse", targetNamespace = "http://endpoint.api.tm.naumkin.ru/", className = "ru.naumkin.tm.api.endpoint.ValidateResponse")
    public void validate(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    ) throws Exception;

    @WebMethod
    @Action(input = "http://endpoint.api.tm.naumkin.ru/ISessionEndpoint/getUserIdRequest", output = "http://endpoint.api.tm.naumkin.ru/ISessionEndpoint/getUserIdResponse", fault = {@FaultAction(className = Exception.class, value = "http://endpoint.api.tm.naumkin.ru/ISessionEndpoint/getUserId/Fault/Exception")})
    @RequestWrapper(localName = "getUserId", targetNamespace = "http://endpoint.api.tm.naumkin.ru/", className = "ru.naumkin.tm.api.endpoint.GetUserId")
    @ResponseWrapper(localName = "getUserIdResponse", targetNamespace = "http://endpoint.api.tm.naumkin.ru/", className = "ru.naumkin.tm.api.endpoint.GetUserIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String getUserId(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    ) throws Exception;

    @WebMethod
    @Action(input = "http://endpoint.api.tm.naumkin.ru/ISessionEndpoint/findAllSessionsRequest", output = "http://endpoint.api.tm.naumkin.ru/ISessionEndpoint/findAllSessionsResponse", fault = {@FaultAction(className = Exception.class, value = "http://endpoint.api.tm.naumkin.ru/ISessionEndpoint/findAllSessions/Fault/Exception")})
    @RequestWrapper(localName = "findAllSessions", targetNamespace = "http://endpoint.api.tm.naumkin.ru/", className = "ru.naumkin.tm.api.endpoint.FindAllSessions")
    @ResponseWrapper(localName = "findAllSessionsResponse", targetNamespace = "http://endpoint.api.tm.naumkin.ru/", className = "ru.naumkin.tm.api.endpoint.FindAllSessionsResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<ru.naumkin.tm.api.endpoint.Session> findAllSessions(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    ) throws Exception;

    @WebMethod
    @Action(input = "http://endpoint.api.tm.naumkin.ru/ISessionEndpoint/openRequest", output = "http://endpoint.api.tm.naumkin.ru/ISessionEndpoint/openResponse", fault = {@FaultAction(className = Exception.class, value = "http://endpoint.api.tm.naumkin.ru/ISessionEndpoint/open/Fault/Exception")})
    @RequestWrapper(localName = "open", targetNamespace = "http://endpoint.api.tm.naumkin.ru/", className = "ru.naumkin.tm.api.endpoint.Open")
    @ResponseWrapper(localName = "openResponse", targetNamespace = "http://endpoint.api.tm.naumkin.ru/", className = "ru.naumkin.tm.api.endpoint.OpenResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String open(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    ) throws Exception;

    @WebMethod
    @Action(input = "http://endpoint.api.tm.naumkin.ru/ISessionEndpoint/removeAllSessionsRequest", output = "http://endpoint.api.tm.naumkin.ru/ISessionEndpoint/removeAllSessionsResponse", fault = {@FaultAction(className = Exception.class, value = "http://endpoint.api.tm.naumkin.ru/ISessionEndpoint/removeAllSessions/Fault/Exception")})
    @RequestWrapper(localName = "removeAllSessions", targetNamespace = "http://endpoint.api.tm.naumkin.ru/", className = "ru.naumkin.tm.api.endpoint.RemoveAllSessions")
    @ResponseWrapper(localName = "removeAllSessionsResponse", targetNamespace = "http://endpoint.api.tm.naumkin.ru/", className = "ru.naumkin.tm.api.endpoint.RemoveAllSessionsResponse")
    public void removeAllSessions(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    ) throws Exception;

    @WebMethod
    @Action(input = "http://endpoint.api.tm.naumkin.ru/ISessionEndpoint/persistSessionRequest", output = "http://endpoint.api.tm.naumkin.ru/ISessionEndpoint/persistSessionResponse", fault = {@FaultAction(className = Exception.class, value = "http://endpoint.api.tm.naumkin.ru/ISessionEndpoint/persistSession/Fault/Exception")})
    @RequestWrapper(localName = "persistSession", targetNamespace = "http://endpoint.api.tm.naumkin.ru/", className = "ru.naumkin.tm.api.endpoint.PersistSession")
    @ResponseWrapper(localName = "persistSessionResponse", targetNamespace = "http://endpoint.api.tm.naumkin.ru/", className = "ru.naumkin.tm.api.endpoint.PersistSessionResponse")
    public void persistSession(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    ) throws Exception;

    @WebMethod
    @Action(input = "http://endpoint.api.tm.naumkin.ru/ISessionEndpoint/findOneSessionRequest", output = "http://endpoint.api.tm.naumkin.ru/ISessionEndpoint/findOneSessionResponse", fault = {@FaultAction(className = Exception.class, value = "http://endpoint.api.tm.naumkin.ru/ISessionEndpoint/findOneSession/Fault/Exception")})
    @RequestWrapper(localName = "findOneSession", targetNamespace = "http://endpoint.api.tm.naumkin.ru/", className = "ru.naumkin.tm.api.endpoint.FindOneSession")
    @ResponseWrapper(localName = "findOneSessionResponse", targetNamespace = "http://endpoint.api.tm.naumkin.ru/", className = "ru.naumkin.tm.api.endpoint.FindOneSessionResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ru.naumkin.tm.api.endpoint.Session findOneSession(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    ) throws Exception;

    @WebMethod
    @Action(input = "http://endpoint.api.tm.naumkin.ru/ISessionEndpoint/removeSessionRequest", output = "http://endpoint.api.tm.naumkin.ru/ISessionEndpoint/removeSessionResponse", fault = {@FaultAction(className = Exception.class, value = "http://endpoint.api.tm.naumkin.ru/ISessionEndpoint/removeSession/Fault/Exception")})
    @RequestWrapper(localName = "removeSession", targetNamespace = "http://endpoint.api.tm.naumkin.ru/", className = "ru.naumkin.tm.api.endpoint.RemoveSession")
    @ResponseWrapper(localName = "removeSessionResponse", targetNamespace = "http://endpoint.api.tm.naumkin.ru/", className = "ru.naumkin.tm.api.endpoint.RemoveSessionResponse")
    public void removeSession(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    ) throws Exception;

    @WebMethod
    @Action(input = "http://endpoint.api.tm.naumkin.ru/ISessionEndpoint/mergeSessionRequest", output = "http://endpoint.api.tm.naumkin.ru/ISessionEndpoint/mergeSessionResponse", fault = {@FaultAction(className = Exception.class, value = "http://endpoint.api.tm.naumkin.ru/ISessionEndpoint/mergeSession/Fault/Exception")})
    @RequestWrapper(localName = "mergeSession", targetNamespace = "http://endpoint.api.tm.naumkin.ru/", className = "ru.naumkin.tm.api.endpoint.MergeSession")
    @ResponseWrapper(localName = "mergeSessionResponse", targetNamespace = "http://endpoint.api.tm.naumkin.ru/", className = "ru.naumkin.tm.api.endpoint.MergeSessionResponse")
    public void mergeSession(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    ) throws Exception;
}
