package ru.naumkin.tm.api.endpoint;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.6
 * 2020-05-19T22:24:57.404+07:00
 * Generated source version: 3.3.6
 *
 */
@WebService(targetNamespace = "http://endpoint.api.tm.naumkin.ru/", name = "ISessionEndpoint")
@XmlSeeAlso({ObjectFactory.class})
public interface ISessionEndpoint {

    @WebMethod
    @Action(input = "http://endpoint.api.tm.naumkin.ru/ISessionEndpoint/validateRequest", output = "http://endpoint.api.tm.naumkin.ru/ISessionEndpoint/validateResponse")
    @RequestWrapper(localName = "validate", targetNamespace = "http://endpoint.api.tm.naumkin.ru/", className = "ru.naumkin.tm.api.endpoint.Validate")
    @ResponseWrapper(localName = "validateResponse", targetNamespace = "http://endpoint.api.tm.naumkin.ru/", className = "ru.naumkin.tm.api.endpoint.ValidateResponse")
    public void validate(

        @WebParam(name = "arg0", targetNamespace = "")
        ru.naumkin.tm.api.endpoint.Session arg0
    );

    @WebMethod
    @Action(input = "http://endpoint.api.tm.naumkin.ru/ISessionEndpoint/findAllSessionsRequest", output = "http://endpoint.api.tm.naumkin.ru/ISessionEndpoint/findAllSessionsResponse")
    @RequestWrapper(localName = "findAllSessions", targetNamespace = "http://endpoint.api.tm.naumkin.ru/", className = "ru.naumkin.tm.api.endpoint.FindAllSessions")
    @ResponseWrapper(localName = "findAllSessionsResponse", targetNamespace = "http://endpoint.api.tm.naumkin.ru/", className = "ru.naumkin.tm.api.endpoint.FindAllSessionsResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<ru.naumkin.tm.api.endpoint.Session> findAllSessions(

        @WebParam(name = "arg0", targetNamespace = "")
        ru.naumkin.tm.api.endpoint.Session arg0
    );

    @WebMethod
    @Action(input = "http://endpoint.api.tm.naumkin.ru/ISessionEndpoint/openRequest", output = "http://endpoint.api.tm.naumkin.ru/ISessionEndpoint/openResponse")
    @RequestWrapper(localName = "open", targetNamespace = "http://endpoint.api.tm.naumkin.ru/", className = "ru.naumkin.tm.api.endpoint.Open")
    @ResponseWrapper(localName = "openResponse", targetNamespace = "http://endpoint.api.tm.naumkin.ru/", className = "ru.naumkin.tm.api.endpoint.OpenResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ru.naumkin.tm.api.endpoint.Session open(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebMethod
    @Action(input = "http://endpoint.api.tm.naumkin.ru/ISessionEndpoint/persistSessionsRequest", output = "http://endpoint.api.tm.naumkin.ru/ISessionEndpoint/persistSessionsResponse")
    @RequestWrapper(localName = "persistSessions", targetNamespace = "http://endpoint.api.tm.naumkin.ru/", className = "ru.naumkin.tm.api.endpoint.PersistSessions")
    @ResponseWrapper(localName = "persistSessionsResponse", targetNamespace = "http://endpoint.api.tm.naumkin.ru/", className = "ru.naumkin.tm.api.endpoint.PersistSessionsResponse")
    public void persistSessions(

        @WebParam(name = "arg0", targetNamespace = "")
        ru.naumkin.tm.api.endpoint.Session arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.util.List<ru.naumkin.tm.api.endpoint.Session> arg1
    );

    @WebMethod
    @Action(input = "http://endpoint.api.tm.naumkin.ru/ISessionEndpoint/closeRequest", output = "http://endpoint.api.tm.naumkin.ru/ISessionEndpoint/closeResponse")
    @RequestWrapper(localName = "close", targetNamespace = "http://endpoint.api.tm.naumkin.ru/", className = "ru.naumkin.tm.api.endpoint.Close")
    @ResponseWrapper(localName = "closeResponse", targetNamespace = "http://endpoint.api.tm.naumkin.ru/", className = "ru.naumkin.tm.api.endpoint.CloseResponse")
    public void close(

        @WebParam(name = "arg0", targetNamespace = "")
        ru.naumkin.tm.api.endpoint.Session arg0
    );

    @WebMethod
    @Action(input = "http://endpoint.api.tm.naumkin.ru/ISessionEndpoint/removeAllSessionsRequest", output = "http://endpoint.api.tm.naumkin.ru/ISessionEndpoint/removeAllSessionsResponse")
    @RequestWrapper(localName = "removeAllSessions", targetNamespace = "http://endpoint.api.tm.naumkin.ru/", className = "ru.naumkin.tm.api.endpoint.RemoveAllSessions")
    @ResponseWrapper(localName = "removeAllSessionsResponse", targetNamespace = "http://endpoint.api.tm.naumkin.ru/", className = "ru.naumkin.tm.api.endpoint.RemoveAllSessionsResponse")
    public void removeAllSessions(

        @WebParam(name = "arg0", targetNamespace = "")
        ru.naumkin.tm.api.endpoint.Session arg0
    );

    @WebMethod
    @Action(input = "http://endpoint.api.tm.naumkin.ru/ISessionEndpoint/findOneSessionRequest", output = "http://endpoint.api.tm.naumkin.ru/ISessionEndpoint/findOneSessionResponse")
    @RequestWrapper(localName = "findOneSession", targetNamespace = "http://endpoint.api.tm.naumkin.ru/", className = "ru.naumkin.tm.api.endpoint.FindOneSession")
    @ResponseWrapper(localName = "findOneSessionResponse", targetNamespace = "http://endpoint.api.tm.naumkin.ru/", className = "ru.naumkin.tm.api.endpoint.FindOneSessionResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ru.naumkin.tm.api.endpoint.Session findOneSession(

        @WebParam(name = "arg0", targetNamespace = "")
        ru.naumkin.tm.api.endpoint.Session arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebMethod
    @Action(input = "http://endpoint.api.tm.naumkin.ru/ISessionEndpoint/validateAdminRequest", output = "http://endpoint.api.tm.naumkin.ru/ISessionEndpoint/validateAdminResponse")
    @RequestWrapper(localName = "validateAdmin", targetNamespace = "http://endpoint.api.tm.naumkin.ru/", className = "ru.naumkin.tm.api.endpoint.ValidateAdmin")
    @ResponseWrapper(localName = "validateAdminResponse", targetNamespace = "http://endpoint.api.tm.naumkin.ru/", className = "ru.naumkin.tm.api.endpoint.ValidateAdminResponse")
    public void validateAdmin(

        @WebParam(name = "arg0", targetNamespace = "")
        ru.naumkin.tm.api.endpoint.Session arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        ru.naumkin.tm.api.endpoint.RoleType arg1
    );

    @WebMethod
    @Action(input = "http://endpoint.api.tm.naumkin.ru/ISessionEndpoint/closeAllRequest", output = "http://endpoint.api.tm.naumkin.ru/ISessionEndpoint/closeAllResponse")
    @RequestWrapper(localName = "closeAll", targetNamespace = "http://endpoint.api.tm.naumkin.ru/", className = "ru.naumkin.tm.api.endpoint.CloseAll")
    @ResponseWrapper(localName = "closeAllResponse", targetNamespace = "http://endpoint.api.tm.naumkin.ru/", className = "ru.naumkin.tm.api.endpoint.CloseAllResponse")
    public void closeAll(

        @WebParam(name = "arg0", targetNamespace = "")
        ru.naumkin.tm.api.endpoint.Session arg0
    );

    @WebMethod
    @Action(input = "http://endpoint.api.tm.naumkin.ru/ISessionEndpoint/signRequest", output = "http://endpoint.api.tm.naumkin.ru/ISessionEndpoint/signResponse")
    @RequestWrapper(localName = "sign", targetNamespace = "http://endpoint.api.tm.naumkin.ru/", className = "ru.naumkin.tm.api.endpoint.Sign")
    @ResponseWrapper(localName = "signResponse", targetNamespace = "http://endpoint.api.tm.naumkin.ru/", className = "ru.naumkin.tm.api.endpoint.SignResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ru.naumkin.tm.api.endpoint.Session sign(

        @WebParam(name = "arg0", targetNamespace = "")
        ru.naumkin.tm.api.endpoint.Session arg0
    );

    @WebMethod
    @Action(input = "http://endpoint.api.tm.naumkin.ru/ISessionEndpoint/getListSessionRequest", output = "http://endpoint.api.tm.naumkin.ru/ISessionEndpoint/getListSessionResponse")
    @RequestWrapper(localName = "getListSession", targetNamespace = "http://endpoint.api.tm.naumkin.ru/", className = "ru.naumkin.tm.api.endpoint.GetListSession")
    @ResponseWrapper(localName = "getListSessionResponse", targetNamespace = "http://endpoint.api.tm.naumkin.ru/", className = "ru.naumkin.tm.api.endpoint.GetListSessionResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<ru.naumkin.tm.api.endpoint.Session> getListSession(

        @WebParam(name = "arg0", targetNamespace = "")
        ru.naumkin.tm.api.endpoint.Session arg0
    );

    @WebMethod
    @Action(input = "http://endpoint.api.tm.naumkin.ru/ISessionEndpoint/persistSessionRequest", output = "http://endpoint.api.tm.naumkin.ru/ISessionEndpoint/persistSessionResponse")
    @RequestWrapper(localName = "persistSession", targetNamespace = "http://endpoint.api.tm.naumkin.ru/", className = "ru.naumkin.tm.api.endpoint.PersistSession")
    @ResponseWrapper(localName = "persistSessionResponse", targetNamespace = "http://endpoint.api.tm.naumkin.ru/", className = "ru.naumkin.tm.api.endpoint.PersistSessionResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ru.naumkin.tm.api.endpoint.Session persistSession(

        @WebParam(name = "arg0", targetNamespace = "")
        ru.naumkin.tm.api.endpoint.Session arg0
    );

    @WebMethod
    @Action(input = "http://endpoint.api.tm.naumkin.ru/ISessionEndpoint/removeSessionRequest", output = "http://endpoint.api.tm.naumkin.ru/ISessionEndpoint/removeSessionResponse")
    @RequestWrapper(localName = "removeSession", targetNamespace = "http://endpoint.api.tm.naumkin.ru/", className = "ru.naumkin.tm.api.endpoint.RemoveSession")
    @ResponseWrapper(localName = "removeSessionResponse", targetNamespace = "http://endpoint.api.tm.naumkin.ru/", className = "ru.naumkin.tm.api.endpoint.RemoveSessionResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ru.naumkin.tm.api.endpoint.Session removeSession(

        @WebParam(name = "arg0", targetNamespace = "")
        ru.naumkin.tm.api.endpoint.Session arg0
    );

    @WebMethod
    @Action(input = "http://endpoint.api.tm.naumkin.ru/ISessionEndpoint/isValidRequest", output = "http://endpoint.api.tm.naumkin.ru/ISessionEndpoint/isValidResponse")
    @RequestWrapper(localName = "isValid", targetNamespace = "http://endpoint.api.tm.naumkin.ru/", className = "ru.naumkin.tm.api.endpoint.IsValid")
    @ResponseWrapper(localName = "isValidResponse", targetNamespace = "http://endpoint.api.tm.naumkin.ru/", className = "ru.naumkin.tm.api.endpoint.IsValidResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean isValid(

        @WebParam(name = "arg0", targetNamespace = "")
        ru.naumkin.tm.api.endpoint.Session arg0
    );

    @WebMethod
    @Action(input = "http://endpoint.api.tm.naumkin.ru/ISessionEndpoint/mergeSessionRequest", output = "http://endpoint.api.tm.naumkin.ru/ISessionEndpoint/mergeSessionResponse")
    @RequestWrapper(localName = "mergeSession", targetNamespace = "http://endpoint.api.tm.naumkin.ru/", className = "ru.naumkin.tm.api.endpoint.MergeSession")
    @ResponseWrapper(localName = "mergeSessionResponse", targetNamespace = "http://endpoint.api.tm.naumkin.ru/", className = "ru.naumkin.tm.api.endpoint.MergeSessionResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ru.naumkin.tm.api.endpoint.Session mergeSession(

        @WebParam(name = "arg0", targetNamespace = "")
        ru.naumkin.tm.api.endpoint.Session arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );
}
