
package ru.naumkin.tm.api.endpoint;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.3.6
 * 2020-05-22T19:31:29.061+07:00
 * Generated source version: 3.3.6
 */

@WebFault(name = "JAXBException", targetNamespace = "http://endpoint.api.tm.naumkin.ru/")
public class JAXBException_Exception extends java.lang.Exception {

    private ru.naumkin.tm.api.endpoint.JAXBException jaxbException;

    public JAXBException_Exception() {
        super();
    }

    public JAXBException_Exception(String message) {
        super(message);
    }

    public JAXBException_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public JAXBException_Exception(String message, ru.naumkin.tm.api.endpoint.JAXBException jaxbException) {
        super(message);
        this.jaxbException = jaxbException;
    }

    public JAXBException_Exception(String message, ru.naumkin.tm.api.endpoint.JAXBException jaxbException, java.lang.Throwable cause) {
        super(message, cause);
        this.jaxbException = jaxbException;
    }

    public ru.naumkin.tm.api.endpoint.JAXBException getFaultInfo() {
        return this.jaxbException;
    }
}
