package ru.naumkin.tm.enpoint;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;
import ru.naumkin.tm.api.endpoint.ISessionEndpoint;

/**
 * This class was generated by Apache CXF 3.3.6
 * 2020-05-19T22:24:57.410+07:00
 * Generated source version: 3.3.6
 *
 */
@WebServiceClient(name = "SessionEndpointService",
                  wsdlLocation = "http://localhost:8080/SessionEndpoint?wsdl",
                  targetNamespace = "http://enpoint.tm.naumkin.ru/")
public class SessionEndpointService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://enpoint.tm.naumkin.ru/", "SessionEndpointService");
    public final static QName SessionEndpointPort = new QName("http://enpoint.tm.naumkin.ru/", "SessionEndpointPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/SessionEndpoint?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SessionEndpointService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/SessionEndpoint?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SessionEndpointService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SessionEndpointService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SessionEndpointService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public SessionEndpointService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public SessionEndpointService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public SessionEndpointService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns ISessionEndpoint
     */
    @WebEndpoint(name = "SessionEndpointPort")
    public ISessionEndpoint getSessionEndpointPort() {
        return super.getPort(SessionEndpointPort, ISessionEndpoint.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ISessionEndpoint
     */
    @WebEndpoint(name = "SessionEndpointPort")
    public ISessionEndpoint getSessionEndpointPort(WebServiceFeature... features) {
        return super.getPort(SessionEndpointPort, ISessionEndpoint.class, features);
    }

}
